gadgetlikelihood("likelihood", gd$dir, missingOkay=T) %>%
    gadget_update("penalty",
                  name = "bounds",
                  weight = "0.5",
                  data = data.frame(
                      switch = c("default"),
                      power = c(2),
                      upperW=10000,
                      lowerW=10000,
                      stringsAsFactors = FALSE)) %>%
    gadget_update("understocking",
                  name = "understocking",
                  weight = "100") %>%
    gadget_update("catchdistribution",
                  name = "ldist.spr",
                  weight = 1,
                  data = ldist_spr[[1]],
                  fleetnames = c("spr"),
                  stocknames = stock) %>%
    gadget_update("catchdistribution",
                  name = "aldist.spr",
                  weight = 1,
                  data = aldist_spr[[1]],
                  fleetnames = c("spr"),
                  stocknames = stock) %>%
    gadget_update("catchdistribution",
                  name = "ldist.aut",
                  weight = 1,
                  data = ldist_aut[[1]],
                  fleetnames = c("aut"),
                  stocknames = stock) %>%
    gadget_update("catchdistribution",
                  name = "aldist.aut",
                  weight = 1,
                  data = aldist_aut[[1]],
                  fleetnames = c("aut"),
                  stocknames = stock) %>%
    gadget_update("catchdistribution",
                  name = "ldist.comm",
                  weight = 1,
                  data = ldist_comm[[1]],
                  fleetnames = c("comm"),
                  stocknames = stock) %>%
    gadget_update("catchdistribution",
                  name = "aldist.comm",
                  weight = 1,
                  data = aldist_comm[[1]],
                  fleetnames = c("comm"),
                  stocknames = stock) %>%
     gadget_update("surveyindices",
                   name = "spr.si.0.18",
                   weight = 1,
                   data = spr_si_0_18[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stocknames) %>%
     gadget_update("surveyindices",
                   name = "spr.si.18.36",
                   weight = 1,
                   data = spr_si_18_36[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stocknames) %>%
     gadget_update("surveyindices",
                   name = "spr.si.36.48",
                   weight = 1,
                   data = spr_si_36_48[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock) %>%
     gadget_update("surveyindices",
                   name = "spr.si.48.60",
                   weight = 1,
                   data = spr_si_48_60[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock) %>%
     gadget_update("surveyindices",
                   name = "spr.si.60.70",
                   weight = 1,
                   data = spr_si_60_70[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock) %>%
     gadget_update("surveyindices",
                   name = "spr.si.70.pl",
                   weight = 1,
                   data = spr_si_70_pl[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock) %>%
     gadget_update("surveyindices",
                   name = "aut.si.0.18",
                   weight = 1,
                   data = aut_si_0_18[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stocknames) %>%
     gadget_update("surveyindices",
                   name = "aut.si.18.36",
                   weight = 1,
                   data = aut_si_18_36[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stocknames) %>%
     gadget_update("surveyindices",
                   name = "aut.si.36.48",
                   weight = 1,
                   data = aut_si_36_48[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock) %>%
     gadget_update("surveyindices",
                   name = "aut.si.48.60",
                   weight = 1,
                   data = aut_si_48_60[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock) %>%
     gadget_update("surveyindices",
                   name = "aut.si.60.70",
                   weight = 1,
                   data = aut_si_60_70[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock) %>%
     gadget_update("surveyindices",
                   name = "aut.si.70.pl",
                   weight = 1,
                   data = aut_si_70_pl[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock) %>%
    write.gadget.file(gd$dir)
