gadgetlikelihood("likelihood", gd$dir, missingOkay=T) %>%
    gadget_update("penalty",
                  name = "bounds",
                  weight = "0.5",
                  data = data.frame(
                      switch = c("default"),
                      power = c(2),
                      upperW=10000,
                      lowerW=10000,
                      stringsAsFactors = FALSE)) %>%
    gadget_update("understocking",
                  name = "understocking",
                  weight = "100") %>%
    gadget_update("catchdistribution",
                  name = "ldist.spr",
                  weight = 1,
                  data = ldist_spr[[1]],
                  fleetnames = c("spr"),
                  stocknames = stocknames) %>%
    gadget_update("catchdistribution",
                  name = "aldist.spr",
                  weight = 1,
                  data = aldist_spr[[1]],
                  fleetnames = c("spr"),
                  stocknames = stocknames) %>%
    gadget_update("catchdistribution",
                  name = "ldist.aut",
                  weight = 1,
                  data = ldist_aut[[1]],
                  fleetnames = c("aut"),
                  stocknames = stocknames) %>%
    gadget_update("catchdistribution",
                  name = "aldist.aut",
                  weight = 1,
                  data = aldist_aut[[1]],
                  fleetnames = c("aut"),
                  stocknames = stocknames) %>%
    gadget_update("catchdistribution",
                  name = "ldist.comm",
                  weight = 1,
                  data = ldist_comm[[1]],
                  fleetnames = c("comm"),
                  stocknames = stock) %>%
    gadget_update("catchdistribution",
                  name = "aldist.comm",
                  weight = 1,
                  data = aldist_comm[[1]],
                  fleetnames = c("comm"),
                  stocknames = stock) %>%
     gadget_update("surveyindices",
                   name = "spr.si.0.15",
                   weight = 1,
                   data = spr_si_0_15[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock0) %>%
     gadget_update("surveyindices",
                   name = "spr.si.15.28",
                   weight = 1,
                   data = spr_si_15_28[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock0) %>%
     gadget_update("surveyindices",
                   name = "spr.si.28.43",
                   weight = 1,
                   data = spr_si_28_43[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock) %>%
     gadget_update("surveyindices",
                   name = "spr.si.43.55",
                   weight = 1,
                   data = spr_si_43_55[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock) %>%
     gadget_update("surveyindices",
                   name = "spr.si.55.65",
                   weight = 1,
                   data = spr_si_55_65[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock) %>%
     gadget_update("surveyindices",
                   name = "spr.si.65.pl",
                   weight = 1,
                   data = spr_si_65_pl[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock) %>%
     gadget_update("surveyindices",
                   name = "aut.si.0.20",
                   weight = 1,
                   data = aut_si_0_20[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock0) %>%
     gadget_update("surveyindices",
                   name = "aut.si.20.35",
                   weight = 1,
                   data = aut_si_20_35[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock0) %>%
     gadget_update("surveyindices",
                   name = "aut.si.35.48",
                   weight = 1,
                   data = aut_si_35_48[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock) %>%
     gadget_update("surveyindices",
                   name = "aut.si.48.60",
                   weight = 1,
                   data = aut_si_48_60[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock) %>%
     gadget_update("surveyindices",
                   name = "aut.si.60.70",
                   weight = 1,
                   data = aut_si_60_70[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock) %>%
     gadget_update("surveyindices",
                   name = "aut.si.70.pl",
                   weight = 1,
                   data = aut_si_70_pl[[1]],
                   fittype = "fixedslopeloglinearfit",
                   slope = 1,
                   stocknames = stock) %>%
    write.gadget.file(gd$dir)
