gadgetlikelihood('likelihood', gd$dir, missingOkay=T) %>%
    gadget_update('penalty',
                  name = "bounds",
                  weight = "0.5",
                  data = data.frame(
                      switch = c("default"),
                      power = c(2),
                      upperW=10000,
                      lowerW=10000,
                      stringsAsFactors = FALSE)) %>%
    gadget_update('understocking',
                  name = 'understocking',
                  weight = '100') %>%
    gadget_update('catchdistribution',
                  name = 'ldist.spr',
                  weight = 1,
                  data = ldist.igfs[[1]],
                  fleetnames = c('spr'),
                  stocknames = stocknames) %>%
    gadget_update('catchdistribution',
                  name = 'aldist.spr',
                  weight = 1,
                  data = aldist.igfs[[1]],
                  fleetnames = c('spr'),
                  stocknames = stocknames) %>%
    gadget_update('catchdistribution',
                  name = 'ldist.aut',
                  weight = 1,
                  data = ldist.aut[[1]],
                  fleetnames = c('aut'),
                  stocknames = stocknames) %>%
    gadget_update('catchdistribution',
                  name = 'aldist.aut',
                  weight = 1,
                  data = aldist.aut[[1]],
                  fleetnames = c('aut'),
                  stocknames = stocknames) %>%
    gadget_update('catchdistribution',
                  name = 'ldist.comm',
                  weight = 1,
                  data = ldist.comm[[1]],
                  fleetnames = c('comm'),
                  stocknames = stocknames) %>%
    gadget_update('catchdistribution',
                  name = 'aldist.comm',
                  weight = 1,
                  data = aldist.comm[[1]],
                  fleetnames = c('comm'),
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'spr.si.0.20',
                  weight = 1,
                  data = spr.si.0.20[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'spr.si.20.35',
                  weight = 1,
                  data = spr.si.20.35[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'spr.si.35.45',
                  weight = 1,
                  data = spr.si.35.45[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'spr.si.45.60',
                  weight = 1,
                  data = spr.si.45.60[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'spr.si.60.80',
                  weight = 1,
                  data = spr.si.60.80[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stock) %>%
    gadget_update('surveyindices',
                  name = 'spr.si.80.pl',
                  weight = 1,
                  data = spr.si.80.pl[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stock) %>%
    gadget_update('surveyindices',
                  name = 'aut.si.0.20',
                  weight = 1,
                  data = aut.si.0.20[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'aut.si.20.35',
                  weight = 1,
                  data = aut.si.20.35[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'aut.si.35.45',
                  weight = 1,
                  data = aut.si.35.45[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'aut.si.45.60',
                  weight = 1,
                  data = aut.si.45.60[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stocknames) %>%
    gadget_update('surveyindices',
                  name = 'aut.si.60.80',
                  weight = 1,
                  data = aut.si.60.80[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stock) %>%
    gadget_update('surveyindices',
                  name = 'aut.si.80.pl',
                  weight = 1,
                  data = aut.si.80.pl[[1]],
                  fittype = 'fixedslopeloglinearfit',
                  slope = 1,
                  stocknames = stock) %>%
    write.gadget.file(gd$dir)